{{- if .Values.trustcenter.secret.create }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trustcenter-app-secret-ext
  namespace: trustcenter
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: trustcenter-ui-app-secret
    creationPolicy: Owner
  data:
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: R2_ACCOUNT_ID
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: R2_SECRET_ACCESS_KEY
{{- end }}
