version: 0.46.2
apiVersion: v2
appVersion: "v0.46.2"
description: A Helm chart to deploy the core Openlane server
name: openlane
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/core
home: https://docs.theopenlane.io
