version: 0.1.0
apiVersion: v2
appVersion: 1.0.0
description: A Helm chart to deploy External Secrets Operator for Openlane
name: openlane-eso
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/openlane-infra
home: https://docs.theopenlane.io
dependencies:
  - name: grafana
    version: 10.0.0
    repository: https://grafana.github.io/helm-charts
    alias: grafana
  - name: oauth2-proxy
    version: 9.0.0
    repository: https://oauth2-proxy.github.io/manifests
    alias: oauth2
